### ISSUE TITLE
DSE module

### ISSUE THREAD

**Issue by hbai98** [lipeng-gu/PointeNet#1]
Hi guys, I noticed your imported package pointnet2_ops_lib is missing. Check it.

**Comment by lipeng-gu** [comment]
I don't understand what you mean. But, before import the package, you need to run ''pip install pointnet2_ops_lib/.''

**Comment by hbai98** [comment]
Thanks! BTW, where is the DSE module that allocates attention to remote points?

**Comment by lipeng-gu** [comment]
> Thanks! BTW, where is the DSE module that allocates attention to remote points?
DSE needs to be inserted into a 3D target detection network, which is different from this code repository. Therefore, we did not add it to this code repository. However, DSE is simple to understand and reproduce.

**Comment by hbai98** [comment]
Thank you!
